In [4]:
from __future__ import print_function
from __future__ import division
from __future__ import absolute_import

import numpy as np
import sys
import pickle
import pandas as pd

import sklearn.metrics as met
from imblearn.over_sampling import SMOTE

#import keras
#from keras import regularizers
#from keras.models import Sequential
#from keras.layers import Dense, Dropout

In [62]:
domains_df = pd.read_csv('../../domainsAll2.csv', index_col=0, header=None)

In [10]:
domains_df

1      2      3      4      5      6      7      8      9      \
0                                                                          
6416           0      0      0      0      0      0      0      0      0   
2318           0      0      0      0      0      0      0      0      0   
84665          0      0      0      0      0      0      0      0      0   
88             0      0      0      0      0      0      0      0      0   
90             0      0      0      0      0      0      0      0      0   
2339           0      0      0      0      0      0      0      0      0   
2624           0      0      0      0      0      0      0      0      0   
5371           0      0      0      0      0      0      0      0      0   
6118           0      0      0      0      0      0      0      0      0   
6774           0      0      0      0      0      0      0      0      0   
375            0      0      0      0      0      0      0      0      0   
23163          0      0      0      0      0      0      0      0      0   
377            0      0      0      0      0      0      0      0      0   
23647          0      0      0      0      0      0      0      0      0   
27236          0      0      0      0      0      0      0      0      0   
54464          0      0      0      0      0      0      0      0      0   
226            0      0      0      0      0      0      0      0      0   
351            0      0      0      0      0      0      0      0      0   
10513          0      0      0      0      0      0      0      0      0   
333            0      0      0      0      0      0      0      0      0   
1600           0      0      0      0      0      0      0      0      0   
10370          0      0      0      0      0      0      0      0      0   
7020           0      0      0      0      0      0      0      0      0   
2033           0      0      0      0      0      0      0      0      0   
338            0      0      0      0      0      0      0      0      0   
4547           0      0      0      0      0      0      0      0      0   
409            0      0      0      0      0      0      0      0      0   
5900           0      0      0      0      0      0      0      0      0   
1436           0      0      0      0      0      0      0      0      0   
2885           0      0      0      0      0      0      0      0      0   
...          ...    ...    ...    ...    ...    ...    ...    ...    ...   
100361133      0      0      0      0      0      0      0      0      0   
100361427      0      0      0      0      0      0      0      0      0   
100363620      0      0      0      0      0      0      0      0      0   
100363860      0      0      0      0      0      0      0      0      0   
100366048      0      0      0      0      0      0      0      0      0   
689805         0      0      0      0      0      0      0      0      0   
64539          0      0      0      0      0      0      0      0      0   
681284         0      0      0      0      0      0      0      0      0   
29670          0      0      0      0      0      0      0      0      0   
140661         0      0      0      0      0      0      0      0      0   
27139          0      0      0      0      0      0      0      0      0   
100365943      0      0      0      0      0      0      0      0      0   
100359583      0      0      0      0      0      0      0      0      0   
100360508      0      0      0      0      0      0      0      0      0   
408248         0      0      0      0      0      0      0      0      0   
100361008      0      0      0      0      0      0      0      0      0   
23300          0      0      0      0      0      0      0      0      0   
71472          0      0      0      0      0      0      0      0      0   
131377         0      0      0      0      0      0      0      0      0   
56203          0      0      0      0      0      0      0 

In [18]:
domains_df.sort_index()

1      2      3      4      5      6      7      8      9      \
0                                                                          
1              0      0      0      0      0      0      0      0      0   
2              0      0      0      0      0      0      0      0      0   
9              0      0      0      0      0      0      0      0      0   
10             0      0      0      0      0      0      0      0      0   
12             0      0      0      0      0      0      0      0      0   
13             0      0      0      0      0      0      0      0      0   
14             0      0      0      0      0      0      0      0      0   
15             0      0      0      0      0      0      0      0      0   
16             0      0      0      0      0      0      0      0      0   
18             0      0      0      0      0      0      0      0      0   
19             0      0      0      0      0      0      0      0      0   
20             0      0      0      0      0      0      0      0      0   
21             0      0      0      0      0      0      0      0      0   
22             0      0      0      0      0      0      0      0      0   
23             0      0      0      0      0      0      0      0      0   
24             0      0      0      0      0      0      0      0      0   
25             0      0      0      0      0      0      0      0      0   
27             0      0      0      0      0      0      0      0      0   
28             0      0      0      0      0      0      0      0      0   
29             0      0      0      0      1      0      0      0      0   
30             0      0      0      0      0      0      0      0      0   
31             0      0      0      0      0      0      0      0      0   
32             0      0      0      0      0      0      0      0      0   
33             0      0      0      0      0      0      0      0      0   
34             0      0      0      0      0      0      0      0      0   
35             0      0      0      0      0      0      0      0      0   
36             0      0      0      0      0      0      0      0      0   
37             0      0      0      0      0      0      0      0      0   
38             0      0      0      0      0      0      0      0      0   
39             0      0      0      0      0      0      0      0      0   
...          ...    ...    ...    ...    ...    ...    ...    ...    ...   
100526767      0      0      0      0      0      0      0      0      0   
100526783      0      0      0      0      0      0      0      0      0   
100526794      0      0      0      0      0      0      0      0      0   
100526832      0      0      0      0      0      0      0      0      0   
100526842      0      0      0      0      0      0      0      0      0   
100527949      0      0      0      0      0      0      0      0      0   
100527963      0      0      0      0      0      0      0      0      0   
100528064      0      0      0      0      0      0      0      0      0   
100529063      0      0      0      0      0      0      0      0      0   
100529097      0      0      0      0      0      0      0      0      0   
100529144      0      0      0      0      0      0      0      0      0   
100529239      0      0      0      0      0      0      0      0      0   
100529241      0      0      0      0      0      0      0      0      0   
100529251      0      0      0      0      0      0      0      0      0   
100529257      0      0      0      0      0      0      0      0      0   
100529261      0      0      0      0      0      0      0      0      0   
100533106      0      0      0      0      0      0      0      0      0   
100533467      0      0      0      0      0      0      0      0      0   
100533496      0      0      0      0      0      0      0      0      0   
100616101      0      0      0      0      0      0      0 

In [25]:
names = np.load('../arrays/names.npy')

In [63]:
dom_names = np.array(domains_df.index, dtype=int)

In [65]:
np.sort(dom_names)

array([        1,         2,         9, ..., 102288414, 102724023,
       102724594])

In [66]:
np.sort(names)

array([        1,         2,         9, ..., 102288414, 102724023,
       102724594])

In [37]:
np.in1d(names, dom_names).astype(int)

array([1, 1, 1, ..., 1, 1, 1])

In [64]:
np.sort(names[np.invert(np.in1d(names,dom_names))])

array([], dtype=int64)

In [50]:
np.savetxt('../../missing_proteins.txt',np.sort(names[np.invert(np.in1d(names,dom_names))]), fmt='%s')

In [61]:
np.ceil(1/2)

1.0

In [ ]:
def gen_batch(coord, labels, domains, batchsize):
    batches = np.ceil(coord.shape[0]/batchsize)
    for i in range(batches):
        coord1 = 
        domains1 = 
        coord2 = 
        domains2 = 
        batch_data = np.concatenate(coord1, coord2, domains1, domains2)
        targets = labels[batches*batchsize:(batches+1)*batchsize]
        yield (batch_data, tagets)

In [56]:
def test():
    for i in range(0,10,3):
        yield (i,2)

In [53]:
test()

<generator object test at 0x7f6f0318fc50>

In [57]:
for i in test():
    print(i)

(0, 2)
(3, 2)
(6, 2)
(9, 2)
