In [1]:
import numpy as np

In [2]:
coord = np.load('../arrays/4D_coord_4x16k.npy')

In [3]:
coord.shape

(16109, 4)

In [4]:
shape = int((coord.shape[0]*coord.shape[0]-coord.shape[0])/2.0)
inter_coord = np.zeros([shape,coord.shape[1]*2])
count = 0

for i in range(0,coord.shape[0]):
    for j in range(0,coord.shape[0]-(1+i)):
        inter_coord[count,0:coord.shape[1]] = coord[i]
        count += 1

In [5]:
count = 0

for i in range(0,coord.shape[0]):
    for j in range(0+i+1,coord.shape[0]):
        inter_coord[count,coord.shape[1]:coord.shape[1]*2] = coord[j]
        count += 1

In [6]:
coord

array([[ 0.7087464 ,  0.7633493 ,  0.66270142,  0.60474653],
       [ 0.23641667,  0.67049566,  0.5557287 ,  0.76851641],
       [ 0.76131548,  0.83006633,  0.55171583,  0.84067548],
       ..., 
       [ 0.83529359,  0.86476634,  0.6170648 ,  0.66866481],
       [ 0.73303502,  0.74962077,  0.79102924,  0.80383237],
       [ 0.3936804 ,  0.76829204,  0.42957095,  0.7802698 ]])

In [7]:
inter_coord

array([[ 0.7087464 ,  0.7633493 ,  0.66270142, ...,  0.67049566,
         0.5557287 ,  0.76851641],
       [ 0.7087464 ,  0.7633493 ,  0.66270142, ...,  0.83006633,
         0.55171583,  0.84067548],
       [ 0.7087464 ,  0.7633493 ,  0.66270142, ...,  0.93574961,
         0.23792443,  0.79882085],
       ..., 
       [ 0.83529359,  0.86476634,  0.6170648 , ...,  0.74962077,
         0.79102924,  0.80383237],
       [ 0.83529359,  0.86476634,  0.6170648 , ...,  0.76829204,
         0.42957095,  0.7802698 ],
       [ 0.73303502,  0.74962077,  0.79102924, ...,  0.76829204,
         0.42957095,  0.7802698 ]])

In [8]:
inter_coord.shape

(129741886, 8)

In [9]:
#np.save('../arrays/coord_all_interactions.npy', inter_coord)

In [10]:
names = np.load('../arrays/names.npy')

In [18]:
names.shape

(16109,)

In [14]:
shape = int((names.shape[0]*names.shape[0]-names.shape[0])/2.0)
inter_names = np.zeros([shape,2])
count = 0

for i in range(0,names.shape[0]):
    for j in range(0,names.shape[0]-(1+i)):
        inter_names[count,0] = names[i]
        count += 1


count = 0

for i in range(0,names.shape[0]):
    for j in range(0+i+1,names.shape[0]):
        inter_names[count,1] = names[j]
        count += 1

In [15]:
names

array([   1,   10,  100, ..., 9993, 9994, 9997])

In [19]:
inter_names.astype(int)

array([[   1,   10],
       [   1,  100],
       [   1, 1000],
       ..., 
       [9993, 9994],
       [9993, 9997],
       [9994, 9997]])

In [17]:
inter_names.shape

(129741886, 2)

In [20]:
np.save('../arrays/names_inter_2x129m.npy', inter_names)